plugins { id 'com.android.application' }
android {
    namespace 'ir.shin.planner'
    compileSdk 34
    defaultConfig {
        applicationId 'ir.shin.planner'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
